abstract class AppState {}
class AppInitialState extends AppState{}
class AppNavBarState extends AppState{}
class CreateDataBaseState extends AppState{}
class InsertDataBaseState extends AppState{}
class GetDataBaseState extends AppState{}
class UpdateDataBaseState extends AppState{}
class DeleteDataBaseState extends AppState{}
class NavBarState extends AppState{}
class DarkModeState extends AppState{}